[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = ["cd campus-lost-found && mvn clean package -DskipTests"]

[start]
cmd = "cd campus-lost-found && java -jar target/campus-lost-found-1.0.0.jar --spring.profiles.active=prod"
